server:
  port: 8001

spring:
  application:
    #应用名字
    name: payment-provider-sentinel
  cloud:
    nacos:
      discovery:
        # Nacos地址
        server-addr: 192.168.174.129:8848
    sentinel:
      transport:
        # Sentinel 控制台地址
        dashboard: 192.168.174.129:8888
        # sentinel api端⼝, 默认8719
        port: 8719
      web-context-unify: false
