server:
  port: 8002

spring:
  main:
    allow-circular-references: true
    allow-bean-definition-overriding: true
  application:
    # 应用名
    name: order-consumer-dubbo-sentinel
  cloud:
    nacos:
      discovery:
        # Nacos服务地址
        server-addr: 192.168.174.129:8848
    sentinel:
      transport:
        # Sentinel 控制台地址
        dashboard: 192.168.174.129:8888
        # sentinel api端⼝, 默认8719
        port: 8719

dubbo:
  cloud:
    # 订阅服务的服务名 *订阅所有服务 想要订阅多个  ,
    subscribed-services: "*"
  registry:
    #注册地址
    address: nacos://192.168.174.129:8848
    timeout: 10000
  protocol:
    # Dubbo服务暴露的协议的配置 dubbo
    name: dubbo
    # 端口从20880开始 自增
    port: -1
